#!/usr/bin/env python3
"""Translate telegramNews.json to trilingual format."""
import json

# Translation dictionary: index -> {zh, en}
translations = {
    0: {
        "zh": "📈 埃尔加矿床：六年增长，改变行业规模\n过去六年，埃尔加矿床的煤炭开采量增长了10倍。这一成果的背后，是数千名专家日复一日的辛勤工作、现代技术的引入以及自有基础设施的有序发展。\n在此期间，埃尔加实施了一系列大型项目：\n▪️ 建成现代化生产综合体；\n▪️ 建成自有铁路干线，连接矿床与海港；\n▪️ 建成机场投入使用，确保可靠的物流和员工运输。\n如今，埃尔加是远东地区最大的煤炭开采项目，也是全国发展最迅速的工业综合体之一。我们将继续提高开采和发运量，巩固领先地位，为未来的增长奠定基础。\n关于埃尔加今日的发展、生产纪录背后的故事以及我们设定的目标——详见《消息》节目报道📺",
        "en": "📈 Elga Deposit: Six Years of Growth Transforming the Industry\nOver the past six years, coal production at the Elga deposit has increased 10-fold. Behind this result is the daily work of thousands of specialists, the introduction of modern technologies, and the systematic development of our own infrastructure.\nDuring this time, large-scale projects were implemented at Elga:\n▪️ A modern production complex was built;\n▪️ A private railway mainline was created, connecting the deposit to the sea port;\n▪️ An airport was commissioned, ensuring reliable logistics and employee delivery.\nToday, Elga is the largest coal mining project in the Far East and one of the most dynamically developing industrial complexes in the country. We continue to increase production and shipment volumes, strengthening our leadership and creating a foundation for further growth.\nWatch the 'Vesti' program report 📺"
    },
    1: {
        "zh": "俄罗斯日快乐！🇷🇺\n对我们来说，这一天是又一个机会，向那些用劳动创造国家当下和未来的人们表示感谢。\n埃尔加综合体的员工每天都在解决复杂任务，确保公司稳定运营，发展生产，实施对整个国家都具有意义的项目。\n任何成果的背后都是专业精神、责任感和团队协作能力。正是这些品质帮助我们不断前进，实现既定目标。\n祝大家身体健康、幸福安康、拥有新的发展机会和事业成功。\n节日快乐！",
        "en": "Happy Russia Day! 🇷🇺\nFor us, this day is another reason to say thank you to the people who create the present and future of our country with their labor.\nEvery day, employees of the Elga complex solve complex tasks, ensure stable company operations, develop production, and implement projects of national significance.\nBehind any results stand professionalism, responsibility, and the ability to work as one team. These qualities help us move forward and achieve our goals.\nWishing you good health, well-being, new opportunities for development, and success in all endeavors.\nHappy holiday!"
    },
    2: {
        "zh": "「埃尔加」——俄罗斯煤炭面向亚洲的橱窗。\n在中国谈判的背景下，中国最大报纸发表了关于「埃尔加」的长篇文章。该项目被定位的不是普通的煤炭开采，而是俄罗斯大型煤炭集群的典范，专门针对亚太市场，尤其是中国——亚洲最大的焦炭消费国。\n我们在短时间内创建了独特的生产综合体，包括采矿企业、太平洋铁路、港口综合体、机场和其他基础设施——埃尔加公司总经理亚历山大·伊萨耶夫表示。\n自2020年以来，埃尔加的开采量从400万吨增长到2025年的3510万吨。今年4月，公司向远东港口发运了334万吨焦煤（KKU），这是俄罗斯单个煤炭开采企业创纪录的月度发运量。\n在物流方面，埃尔加-乌拉克线的现代化将其运输能力从每年1200万吨提升至3000万吨。第二条路线是531公里长的太平洋铁路，两年内建成并于2025年投入运营。它连接矿床与鄂霍次克海沿岸的埃尔加港。\n媒体还特别提到了该码头，它设计为全年运营：四个货运泊位、可接纳10万吨级船舶、煤炭通过传送带输送，以及自有Arc4级破冰拖船。\n与太平洋铁路相结合，该港口为公司提供了通往太平洋的独立出口，减少了对第三方基础设施的依赖，这仍然是煤炭行业的主要瓶颈之一。2027年的目标是通过自有物流系统运输多达5000万吨煤炭。\n🪨 Coala Telegram | MAX",
        "en": "'Elga' as a Showcase of Russian Coal for Asia\nIn the context of negotiations in China, a major article about 'Elga' was published in China's largest newspaper. The project is positioned not as ordinary coal mining, but as an example of a large Russian coal cluster tailored for the Asia-Pacific market and specifically China — Asia's largest coke consumer.\nIn a short time, we created a unique production complex including mining enterprises, the Pacific Railway, a port complex, an airport, and other infrastructure — said Alexander Isaev, General Director of Elga.\nSince 2020, production at Elga has grown from 4 million to 35.1 million tons in 2025. In April, the company shipped 3.34 million tons of coking coal concentrate to Far Eastern ports — a record monthly volume for a single coal mining enterprise in Russia.\nIn logistics, the modernization of the Elga-Ulak line increased its capacity from 12 to 30 million tons per year. The second route is the 531-kilometer Pacific Railway, built in two years and commissioned in 2025. It connects the deposit to the Elga Port on the Sea of Okhotsk coast.\nThe media also highlighted the terminal, designed for year-round operation: four cargo berths, acceptance of vessels up to 100,000 dwt, conveyor coal feeding, and own Arc4-class icebreaking tugs.\nTogether with the Pacific Railway, the port gives the company an independent outlet to the Pacific Ocean and reduces dependence on external infrastructure, which remains one of the main bottlenecks for coal miners. The target for 2027 is to transport up to 50 million tons of coal through its own logistics system.\n🪨 Coala on Telegram | MAX"
    },
    3: {
        "zh": "5月9日，我们庆祝一个几代人心目中最重要的节日。这是关于勇气、爱国精神和不可动摇的胜利信念的提醒。\n我们珍视那些在前线战斗、在后方劳作、在艰难的战后年代重建国家的人们的记忆。多亏了每个家庭中的英雄，我们才能够生活、工作、梦想、养育孩子和建设未来。\n伟大胜利日快乐！祝大家健康、幸福、安康！\n#埃尔加 #雅库特",
        "en": "On May 9, we celebrate a holiday that remains the most important in the lives of several generations. It is a reminder of courage, patriotism, and unwavering faith in Victory.\nWe carefully preserve the memory of those who fought at the front, worked in the rear, and revived the country in the difficult post-war years. Thanks to the heroes in every family, we can live, work, dream, raise children, and build the future.\nHappy Great Victory Day! Wishing you health, happiness, and well-being!\n#Elga #Yakutia"
    },
    4: {
        "zh": "埃尔加！劳动！五月！\n埃尔加以新纪录迎接五一。2026年4月，公司向远东港口发运了333.5万吨煤炭精矿。这样的规模相当于每年4000万吨。这是俄罗斯历史上（包括苏联时期）单个煤炭开采企业月度发运量的新纪录。\n\n「创纪录的指标是合理投资和整个团队紧张工作的必然结果。埃尔加矿床开发项目已成为我国煤炭行业的名片，」——埃尔加公司总经理亚历山大·伊萨耶夫表示。\n#埃尔加 #纪录",
        "en": "Elga! Labor! May!\nElga greets May Day with a new record. In April 2026, the company shipped 3.335 million tons of coal concentrate to Far Eastern ports. Such volumes are equivalent to 40 million tons per year. This is a new record for monthly shipments by a single coal mining enterprise in the entire history of Russia, including the Soviet period.\n\n'The record figures are a logical result of justified investments and the intense work of the entire team. The Elga deposit development project has become a calling card of our country's coal industry,' noted Alexander Isaev, General Director of Elga.\n#Elga #Record"
    },
    5: {
        "zh": "雅库特共和国日快乐！\n今天，这片美丽的土地庆祝一个重要节日——萨哈共和国（雅库特）共和国日。\n对「埃尔加」来说，雅库特不只是地图上的一个点。这是我们工作、发展、创造未来的地区。埃尔加煤炭综合体的发展与萨哈共和国的发展密不可分。\n我们为埃尔加团队的劳动成为共和国历史的一部分、巩固其经济并为该地区居民和全国人民创造新机遇而感到自豪。\n祝愿雅库特及其居民稳定发展、幸福安康、繁荣昌盛！\n#雅库特 #埃尔加",
        "en": "Happy Republic Day, Yakutia!\nToday, this picturesque region celebrates an important holiday — the Day of the Republic of Sakha (Yakutia).\nFor Elga, Yakutia is not just a point on the map. It is the region where we work, develop, and create the future. The development of the Elga coal complex is inextricably linked with the development of the Republic of Sakha.\nWe are proud that the labor of the Elga team becomes part of the republic's history, strengthens its economy, and creates new opportunities for the region's residents and the entire country.\nWishing Yakutia and its people stable development, well-being, and prosperity!\n#Yakutia #Elga"
    },
    6: {
        "zh": "😀 远东煤炭的增长点\n埃尔加公司总经理在《俄罗斯报》专栏中关于远东煤炭增长点的精彩内容。\n↗️ 在整个行业面临困难时期的大背景下，远东仍然是稳定增长的地区。原因在于强大的资源基础、有利的地理位置和已建成的基础设施相结合。\n📈 远东地区集中了超过300亿吨煤炭平衡储量。如果在苏联时期该地区每年开采6000-7000万吨，那么到2025年这一指标达到了1.279亿吨——约占全国总产量的30%。\n⚡️ 主要驱动力是面向亚太市场的出口项目。靠近中国以及港口通道使远东矿床具有竞争力。关键例子是埃尔加矿床：去年这里开采了3510万吨，占远东地区煤炭开采总量的四分之一以上。\n🚀 增长不仅靠开采，还靠物流：埃尔加的私人铁路和自有港口、瓦尼诺的新码头、萨哈林的项目。这提高了供应的稳定性，减轻了东部多边形铁路的压力。\n💪 增长的主要潜力在于内部加工和能源。合理的方式是保留大型发电用煤、在矿床附近建设现代化火电站、发展能源密集型产业，包括冶金业。该地区拥有这一切条件：原料、能源、物流和靠近亚洲市场。\n阅读完整专栏\n#埃尔加 #太平洋铁路 #观点",
        "en": "😀 Growth Points of Far Eastern Coal\nKey points from the column of Elga's General Director in Rossiyskaya Gazeta on growth points for Far Eastern coal.\n↗️ Against the backdrop of a difficult period for the entire industry, the Far East remains a territory of stable growth. The reason is the combination of a powerful raw material base, favorable geography, and created infrastructure.\n📈 More than 30 billion tons of balance coal reserves are concentrated in the Far Eastern Federal District. If during the Soviet period the region mined 60–70 million tons per year, in 2025 the figure reached 127.9 million tons — about 30% of the total Russian volume.\n⚡️ The main driver is export projects oriented towards Asia-Pacific markets. Proximity to China and access to ports make Far Eastern deposits competitive. A key example is the Elga deposit: last year, 35.1 million tons were mined here, more than a quarter of all coal production in the Far East.\n🚀 Growth is ensured not only by mining but also by logistics: a private railway and own port for Elga, a new terminal in Vanino, projects on Sakhalin. This increases supply stability and reduces the load on the Eastern Polygon.\n💪 The main reserve for growth is internal processing and energy. It is rational to preserve coal for large-scale generation, build modern thermal power plants near deposits, and develop energy-intensive industries, including metallurgy. The region has everything for this: raw materials, energy, logistics, and proximity to Asian markets.\nRead the full column\n#Elga #PacificRailway #Opinion"
    },
    7: {
        "zh": "⚡️ 埃尔加实现创纪录的月发运300万吨\n2026年3月，从埃尔加矿床发运了300万吨煤炭。这是该项目历史上最高的月度指标之一。\n发运量增长得益于埃尔加-乌拉克铁路段的现代化改造，以及2025年9月投入运营的531公里长太平洋铁路（ТЖД）的启用。\n在现代化改造框架内，埃尔加-乌拉克段的通过能力从每年400万吨提升至3000万吨。沿途建设了会让站并实现集中控制，引入了独特的运输监控、管理和组织自动化系统，提高了物流的可靠性和效率。\n3月底，在阿穆尔州远东铁路乌拉克站，埃尔加煤炭的发运也创下新纪录——单日9.95万吨，即17列火车。之所以能取得这样的成果，得益于数字技术的引入、所有参与方的协作以及铁路基础设施的发展。\n#埃尔加 #太平洋铁路 #纪录",
        "en": "⚡️ Elga Reaches Record 3 Million Tons Monthly Shipment\nIn March 2026, 3 million tons of coal were shipped from the Elga deposit. This is one of the highest monthly indicators in the project's history.\nThe growth in transportation volumes was facilitated by the modernization of the Elga-Ulak railway section and the commissioning of the 531 km Pacific Railway (Pacific Railway) in September 2025.\nWithin the modernization framework, the throughput capacity of the Elga-Ulak section increased from 4 to 30 million tons per year. Passing loops were built and centralized along the route, and a unique automation system for monitoring, management, and organization of transportation was introduced, increasing logistics reliability and efficiency.\nAt the end of March, a new record for Elga coal shipment was also set at Ulak station of the Far Eastern Railway (Amur Oblast) — 99.5 thousand tons per day, or 17 trains. This result was achieved thanks to the introduction of digital technologies, interaction among all participants in the process, and the development of mainline infrastructure.\n#Elga #PacificRailway #Record"
    },
    8: {
        "zh": "雅库特启用了全国最大的商业pLTE网络\n😀 数字基础设施将埃尔加矿床、马诺尔斯基角的海洋煤炭码头和太平洋铁路连接起来。\n🌎 网络规模超过1万公顷，总长度超过530公里。项目由「埃尔加煤炭」和MegaFon联合实施。\n\n💻 统一的网络实现了矿床、港口和铁路之间的即时数据交换，创造了数字无缝覆盖。\n\n📡 除了为公司员工提供与家人的稳定全天候通讯外，该网络还确保了对整个生产链上的设备、运输和货流的端到端监控——从煤炭开采到港口发运。\n\n🚛 生产部门可以在线控制采矿设备的运行，确保高水平的生产调度和人员预警，以及管理和监控各个系统。\n\n🛰 项目实现了高可靠性语音和中继通信、面向工业应用的高速互联网接入，以及精度达米的定位和遥测服务。此外，还为IIoT解决方案的实施奠定了基础——远程监控和自动化控制系统。\n#埃尔加 #雅库特 #pLTE",
        "en": "Russia's Largest Commercial pLTE Network Launched in Yakutia\n😀 Digital infrastructure connects the Elga coal deposit, the sea coal terminal at Cape Manorsky, and the Pacific Railway.\n🌎 The network scale exceeds 10,000 hectares, with a total length of over 530 km. The project was implemented by Elga Coal and MegaFon.\n\n💻 A unified network enables instant data exchange between the deposit, port, and railway, creating digital seamless coverage.\n\n📡 In addition to stable round-the-clock communication between company employees and their families, the network ensures end-to-end monitoring of equipment, transport, and cargo flows across the entire production chain — from coal mining to port shipment.\n\n🚛 Production services can control mining equipment operations in online mode, ensure a high level of production dispatching and personnel alerting, and management and monitoring of various systems.\n\n🛰 Within the project, high-reliability voice and trunking communication, high-speed Internet access for industrial applications, and positioning and telemetry services with meter-level accuracy were implemented. In addition, a foundation is being created for the introduction of IIoT solutions — remote monitoring and control systems in automated mode.\n#Elga #Yakutia #pLTE"
    },
    9: {
        "zh": "😀 新年快乐2026！\n过去的一年对埃尔加来说是真正具有标志性意义的一年。我们增加了产量，巩固了公司的地位，并迈出了重要一步——开通了太平洋铁路。但我们确信：最重要的发现还在前方。\n新的一年，我们将继续前进，不断发展，引入新的解决方案，并以同样协调和专业的方式工作！\n愿2026年带来稳定和明日的信心。新年快乐！\n#埃尔加 #雅库特 #新年2026",
        "en": "😀 Happy New Year 2026!\nThe outgoing year has been truly landmark for Elga. We increased production, strengthened the company's position, and took an important step — opening the Pacific Railway. But we are confident: the greatest discoveries are still ahead.\nIn the new year, we will continue to move forward, develop, introduce new solutions, and work with the same coordination and professionalism!\nMay 2026 bring stability and confidence in tomorrow. Happy New Year!\n#Elga #Yakutia #NY2026"
    },
    10: {
        "zh": "😀 煤炭行业正经历近几十年来最困难的时期之一。\n在新条件下，哪些解决方案可以确保公司的稳定性——我们梳理了埃尔加公司总经理亚历山大·伊萨耶夫为RBC撰写的专栏中的关键论点。\n#埃尔加 #观点",
        "en": "😀 The coal industry is going through one of the most difficult periods in recent decades.\nWhat solutions can ensure company stability under new conditions — we have analyzed the key theses from the column of Elga General Director Alexander Isaev for RBC.\n#Elga #Opinion"
    },
    11: {
        "zh": "😀 总统为俄罗斯开通了太平洋铁路\n俄罗斯总统弗拉基米尔·普京在第十届东方经济论坛上宣布太平洋铁路投入运营——这是一条全长531公里的独特路线，仅用2年时间建成。\n该项目由「埃尔加」公司实施，基础设施投资达1400亿卢布，创造了3000个新就业岗位。\n太平洋铁路成为俄罗斯首条如此规模的私营铁路，也是继西伯利亚大铁路和贝阿铁路之后的第三条战略动脉。它连接雅库特和哈巴罗夫斯克边疆区，包括6座桥梁、18个会让站和550多个工程设施。新线路的运输能力为每年5000万吨。\n太平洋铁路为国家经济和物流开辟了新的机遇——这是远东乃至整个俄罗斯发展的新方向！\n#埃尔加 #太平洋铁路",
        "en": "😀 President Opens Pacific Railway for Russia\nRussian President Vladimir Putin at the 10th Eastern Economic Forum launched the Pacific Railway — a unique 531 km route built in just 2 years.\nThe project was implemented by Elga, which invested 140 billion rubles in infrastructure and created 3,000 new jobs.\nThe Pacific Railway became the first private railway of such scale in Russia and the third strategic artery alongside the Trans-Siberian and BAM. It connects Yakutia and the Khabarovsk Territory, includes 6 bridges, 18 passing loops, and over 550 engineering facilities. The carrying capacity of the new line is 50 million tons per year.\nThe Pacific Railway opens new opportunities for the country's economy and logistics — a new vector for the development of the Far East and all of Russia!\n#Elga #PacificRailway"
    },
    12: {
        "zh": "📍「埃尔加」在周年东方经济论坛上以运煤车厢造型的展台和大量数字特色精彩亮相。煤炭工人创造性地将严谨的商务风格与真正的艺术相结合。\n最亮眼的「明星」是一个巨大的互动立方体——就像马列维奇将他的「方块」变成了大企业的艺术装置，创意 literally 突破了惯常的边界。这不仅是展览，更是视觉宣言：技术和文化可以用同一种语言交流，共同带来惊喜。\n但最重要的是，炫目的形式背后不失去严肃的内容。该公司正在开发世界上最大的优质焦煤矿床之一，同时构建自己的运输物流综合体。其中包括穿越雅库特和哈巴罗夫斯克边疆区的太平洋铁路，以及位于鄂霍次克海沿岸哈巴罗夫斯克边疆区马诺尔斯基角的海洋煤炭码头。\n新时代的工业公关就应该这样——大胆、有创意、有个性、有态度。\n#东方经济论坛日记",
        "en": "📍 Elga made a bright and bold debut at the anniversary Eastern Economic Forum with its booth in the form of a coal wagon and a bunch of digital features. The coal miners creatively combined a businesslike, strict approach with genuine art.\nThe main 'star' was a huge interactive cube — it's as if Malevich turned his 'Square' into an art object for big business, where ideas literally go beyond the usual. The result was not just an exposition, but a visual manifesto: technology and culture can speak the same language and amaze together.\nBut most importantly, behind the bright form, serious content is not lost. The company is developing one of the world's largest deposits of premium coking coal and simultaneously forming its own transport and logistics complex. It includes the Pacific Railway passing through Yakutia and the Khabarovsk Territory, and a sea coal terminal at Cape Manorsky in the Khabarovsk Territory on the coast of the Sea of Okhotsk.\nThis is what industrial PR of the new era should look like — boldly, creatively, with its own face and character.\n#EEFDiary"
    },
    13: {
        "zh": "😀 矿工节快乐！\n今天，我们向所有向大地深处求索、推动进步高峰的人们致敬。你们的劳动使共同前进成为可能。我们一起开采未来——一步一步，跨越一个又一个地平线，将地球的馈赠转化为国家的成就。\n愿你们的技艺比岩石更坚硬，每个工作日都带来信心和自豪。祝大家身体健康、家庭温暖、取得新成就！\n节日快乐！",
        "en": "😀 Happy Miner's Day!\nToday, we congratulate everyone who, turning to the depths of the earth, reaches the heights of progress. Your labor makes common forward movement possible. We mine the future together — step by step, horizon after horizon, transforming the gifts of the planet into the achievements of the country.\nMay your skill be stronger than rock, and every working day bring confidence and pride. Wishing you good health, family warmth, and new achievements!\nHappy holiday!"
    },
    14: {
        "zh": "♻️ 埃尔加启用混合动力自卸卡车\n⚡️ 首辆三一SET150S矿用混合动力自卸卡车在埃尔加矿床投入使用。该车同时由柴油发动机和电动机驱动，载重达136吨。\n💡 自卸卡车的电动机兼具驱动力和发电机的功能。它配备了现代化的能量回收系统，在制动过程中为电池补充能量，因此电池无需额外充电。\n✅ 得益于双发动机和创新的锂离子电池，车辆功率比未配备混合动力技术的同类车型提高了15%。\n➡️ 采用混合动力的车型可在运营过程中节省高达25%的燃料。车辆配备自动润滑系统，延长了自卸卡车的使用寿命，有助于降低维护成本。\n📈 2025年，「服务+」公司将为埃尔加煤矿综合体的混合动力重型设备车队再添五台这样的机器。",
        "en": "♻️ Hybrid Dump Trucks Launched at Elga\n⚡️ The first SANY SET150S mining hybrid dump truck has started operating at the Elga coal deposit. The machine, which simultaneously works from two engines — diesel and electric — has a payload capacity of 136 tons.\n💡 The electric motor of the dump truck performs the functions of both driving force and generator. It is equipped with a modern regeneration system that replenishes the battery's energy reserve during braking, so the battery does not require additional charging.\n✅ Thanks to the dual engine and innovative lithium-ion battery, the machine's power increases by 15% compared to similar models not equipped with hybrid technologies.\n➡️ The model with a hybrid power plant allows saving up to 25% of fuel during operation. The machine's automatic lubrication system increases the dump truck's service life and helps reduce maintenance costs.\n📈 In 2025, Service Plus will add five more such machines to the fleet of hybrid heavy-duty equipment of the Elga coal complex."
    },
    15: {
        "zh": "😀 「埃尔加煤炭」支持奥伦霍雅库特节\n在「埃尔加煤炭」的支持下，全国节日奥伦霍雅库特节在涅留恩格里举行。\n🎶 今年涅留恩格里区首次承办奥伦霍雅库特节，该节日纪念两个重要日子——伟大卫国战争胜利80周年和涅留恩格里市建市50周年。约1.5万人参加了节日活动。\n✨ 在新落成的民族志综合体「塔斯塔赫」领土上组织的丰富节目包括70多项活动，其中有比赛、体育竞赛、仪式典礼、展览、音乐会和戏剧表演。\n「我们怀着特别的敬意对待故乡的传统和文化。「埃尔加煤炭」是一个代表不同民族的数千人团队，奥伦霍节总能唤起我们的团结感、对光辉历史的尊重和对奥伦霍大地光明未来的信念。祝大家身体健康、家庭幸福！愿奥伦霍（雅库特语意为「丰饶」）增强对明天的信心，留下难忘的记忆，赋予大家活力和灵感！」——「埃尔加煤炭」项目负责人茵娜·洛修克表示祝贺。",
        "en": "😀 Elga Coal Supported Ysyakh Olonkho\nThe national holiday Ysyakh Olonkho was held in Neryungri with the support of Elga Coal.\n🎶 This year, the Neryungri district hosted Ysyakh Olonkho for the first time, dedicated to two significant dates — the 80th anniversary of Victory in the Great Patriotic War and the 50th anniversary of the city of Neryungri. About 15,000 people became participants and guests of the holiday.\n✨ A rich program organized on the territory of the new ethnographic complex 'Taastaakh' consisted of more than 70 events, including competitions, sports competitions, ritual ceremonies, exhibitions, concerts, and theater performances.\n'We treat the traditions and culture of our native land with special reverence. Elga Coal is a multi-thousand team representing the most diverse nationalities, and Ysyakh always evokes in us a sense of unity, respect for the glorious past, and faith in the bright future of the Land of Olonkho. I want to wish everyone good health and family well-being! May Ysyakh, which translates from Yakut as 'abundance,' strengthen confidence in tomorrow, be remembered for bright events, and give vigor and inspiration!' — congratulated Inna Losyuk, head of the Elga Coal project."
    },
    16: {
        "zh": "😀 俄罗斯日——不仅仅是日历上的日期。这是创造能量和团结的象征！我们每天用自己的劳动为祖国的发展和强大做出贡献。\n每一个新煤层、每一车煤炭、每一公里铁路和我们每个人的每一份努力——这一切都构成了未来坚实基础：我们和我们国家的未来。\n愿每个工作日都带来新的伟大胜利！\n#埃尔加 #俄罗斯日",
        "en": "😀 Russia Day is more than a calendar date. It is a symbol of the energy of creation and unity! With our labor, we daily contribute to the development and strength of our Motherland.\nEvery new seam, every wagon of coal, every kilometer of railway, and every effort of each of us — all this lays the foundation for a strong future: ours and our country's.\nMay every working day bring new great victories!\n#Elga #RussiaDay"
    },
    17: {
        "zh": "🌍 埃尔加扩展航线网络\n✈️ 5月，新库兹涅茨克-埃尔加航线首航成功。雅库特航空公司的航班搭载了一百六十多名来自库兹巴斯南部首府的乘客。\n🛄 至此，埃尔加矿床机场已与西伯利亚和远东的主要大城市建立了空中桥梁：新西伯利亚、克拉斯诺亚尔斯克、赤塔、涅留恩格里、雅库茨克和新库兹涅茨克。\n🗓️ 6月，矿场员工还将新增一个航向：6月5日计划开通布拉戈维申斯克航线。\n📈 根据2025年第一季度的结果，埃尔加机场的航班数量比去年同期增长了74%，客流量创纪录地增长了402%，达到近2万人次。\n#埃尔加 #雅库特",
        "en": "🌍 Elga Expands Flight Geography\n✈️ In May, the first flight on the Novokuznetsk-Elga route took place. Yakutia Airlines carried more than 160 passengers from the southern capital of Kuzbass.\n🛄 Thus, the airport of the Elga deposit is now connected by air bridges with the main large cities of Siberia and the Far East: Novosibirsk, Krasnoyarsk, Chita, Neryungri, Yakutsk, and Novokuznetsk.\n🗓️ In June, another destination will open for deposit workers: a flight to Blagoveshchensk is scheduled for June 5.\n📈 According to the results of the first quarter of 2025, the number of flights from Elga Airport increased by 74% compared to the same period last year, and passenger traffic increased by a record 402%, reaching almost 20,000 people.\n#Elga #Yakutia"
    },
    18: {
        "zh": "🔖今天，我们庆祝一个成为不止一代人勇气和英勇象征的日子。5月9日——不仅仅是日历上的日期。\n这是对那些在前线战斗、在后方劳作、为共同胜利奉献一切力量的人们的记忆。\n在每个俄罗斯家庭中，都有亲人经历战争考验的故事。前线照片、泛黄的信件、战斗勋章——我们珍视与过去的联系，铭记和平的代价。\n我们为胜利一代的精神力量、坚韧和自我牺牲感到自豪。几十年过去了，但我们仍然怀着深深的感激之情缅怀英雄们。\n愿我们心中永远怀着对祖先功绩的敬意，愿他们的勇气激励我们珍惜以如此高昂代价赢得的和平。\n胜利日快乐！\n#埃尔加 #雅库特 #胜利80周年",
        "en": "🔖 Today, we celebrate a day that has become a symbol of courage and valor for more than one generation. May 9 is not just a date on the calendar.\nIt is a memory of those who fought at the front and worked in the rear, giving all their strength for the common Victory.\nIn every Russian family, there is a story about loved ones who went through the trials of war. Front-line photographs, yellowed letters, combat awards — we carefully preserve the connection with the past, remembering the price of peace.\nWe are proud of the spiritual strength, resilience, and selflessness of the Victory generation. Decades have passed, but we still remember the heroes with deep gratitude.\nMay respect for the feat of our ancestors always live in our hearts, and may their courage inspire us to cherish the peace won at such a high price.\nHappy Victory Day!\n#Elga #Yakutia #Victory80Years"
    },
    19: {
        "zh": "🇷🇺 「埃尔加煤炭」准备庆祝节日\n🔖在胜利日庆祝活动前夕，公司员工积极参与纪念伟大卫国战争胜利80周年的爱国行动。他们用白色仙鹤和周年主要象征——祖国母亲的形象装饰了涅留恩格里办公室的外墙和窗户。\n⭐ 作为传统「不朽军团」活动的一部分，大楼大厅布置了前线战士——煤炭公司员工家属参战人员的肖像展板。\n🔖 5月9日，「埃尔加煤炭」员工还将参加涅留恩格里和埃尔加矿场的节日活动。\n#埃尔加 #雅库特 #胜利80周年",
        "en": "🇷🇺 Elga Coal Prepares for the Holiday\n🔖 On the eve of Victory Day celebrations, company employees are actively participating in patriotic actions dedicated to the 80th anniversary of Victory in the Great Patriotic War. They decorated the facade and windows of the Neryungri office with white cranes and the main symbol of the anniversary — Motherland.\n⭐ As part of the traditional 'Immortal Regiment' action, the building lobby was decorated with a stand featuring portraits of front-line soldiers — participants of the war from the families of coal company employees.\n🔖 On May 9, Elga Coal employees will also take part in festive events in Neryungri and at the Elga coal complex.\n#Elga #Yakutia #Victory80Years"
    },
    20: {
        "zh": "⚡️埃尔加启动太平洋铁路第二线建设\n埃尔加公司开始建设太平洋铁路（ТЖД）的第二轨道。这将使铁路干线的运输能力从每年3000万吨提升至5000万吨。\n531公里的第二轨道建设已经开始。正在进行路基填筑、边坡加固等工作。\n目前铁路处于试运行模式：已发运200万吨煤炭，所有系统已完成测试，并发现了需要进一步完善的区域。",
        "en": "⚡️ Elga Launches Construction of Second Pacific Railway Line\nElga begins construction of the second track on the Pacific Railway (Pacific Railway). This will increase the carrying capacity of the mainline from 30 to 50 million tons of coal per year from the Elga deposit.\nConstruction of the 531 km second track has already begun. Work is underway on embankment backfilling for the upper track structure and reinforcement of embankment slopes.\nCurrently, the mainline is operating in test mode: 2 million tons of coal have already been shipped, all systems have been checked, and zones for further improvement have been identified."
    },
    21: {
        "zh": "⚡️ 200万吨埃尔加煤炭通过太平洋铁路运出\n从埃尔加矿床通过太平洋铁路已发运200万吨煤炭。自2024年11月以来，铁路处于试运行模式。\n「试运行模式使我们能够在真实条件下测试所有管理系统，发现列车在不同路段运行的细节，并定位需要特别关注的区域，」——埃尔加公司总经理亚历山大·伊萨耶夫强调。\n太平洋铁路于2024年建成。铁路全长531公里，包括会让站和车站在内共626公里。这是俄罗斯私人铁路中的创纪录长度。该国最长私人铁路的运输能力为每年3000万吨煤炭。\n#埃尔加 #太平洋铁路",
        "en": "⚡️ 2 Million Tons of Elga Coal Shipped via Pacific Railway\n2 million tons of coal have been shipped from the Elga deposit via the Pacific Railway. Since November 2024, the railway has been operating in test mode.\n'The test mode allowed us to check all management systems in real conditions, identify nuances of train movement on different sections, and localize zones requiring additional attention,' emphasized Alexander Isaev, General Director of Elga.\nThe Pacific Railway was completed in 2024. The track length is 531 km, and with passing loops and stations — 626 km. This is a record length among private railways in Russia. The carrying capacity of the country's longest private railway is 30 million tons of coal per year.\n#Elga #PacificRailway"
    },
    22: {
        "zh": "😀 在一些动画片中，生产变成了神奇的冒险，普通的工作场所成为创造力和意外发现的空间，角色用魔法工具和奇特机制将想法变成生动的形象。\n埃尔加矿床的故事如果用日本动画大师宫崎骏的方式讲述，可能就是这样的。唯一的区别是，埃尔加的惊人蜕变完全是人力创造的奇迹。\n#埃尔加 #雅库特",
        "en": "😀 In some cartoons, production turns into a magical adventure, ordinary workplaces become spaces for creativity and unexpected discoveries, and characters turn ideas into vivid images with magical tools and whimsical mechanisms.\nThis is how the story of the Elga coal deposit might look if told by the master of Japanese animation Hayao Miyazaki. With the only difference that the amazing transformation of Elga is entirely a man-made miracle.\n#Elga #Yakutia"
    },
    23: {
        "zh": "「埃尔加」机场航线网络新增两个目的地——布拉戈维申斯克和新库兹涅茨克。\n🛫 「埃尔加-新库兹涅茨克-埃尔加」航线首航定于5月23日，后续航班安排在5月24日、6月25日和7月8日。「埃尔加-布拉戈维申斯克-埃尔加」航线将于2025年6月5日开通。\n🗓 航班将由雅库特航空和NordStar航空公司执飞。\n🌎 回顾一下，2025年2月开通了埃尔加-赤塔航线。得益于这些运送员工前往矿场的新航线，「埃尔加」机场现在已与西伯利亚和远东的八个城市建立了空中桥梁，包括涅留恩格里、雅库茨克、新西伯利亚、克麦罗沃和克拉斯诺亚尔斯克。\n🛬 除了扩展航线网络外，航空港基础设施的完善工作也在进行中。年初，机场启用了新的航空加油站，航站楼大楼也进行了大规模现代化改造。这将有助于提高乘客服务质量并增加机场的吞吐量。\n#埃尔加 #雅库特 #埃尔加航空",
        "en": "The Elga Airport route network has been supplemented with two new destinations — Blagoveshchensk and Novokuznetsk.\n🛫 The first flight on the 'Elga-Novokuznetsk-Elga' route is scheduled for May 23, with subsequent flights on May 24, June 25, and July 8. The flight on the 'Elga-Blagoveshchensk-Elga' route will take place on June 5, 2025.\n🗓 Flights will be operated by Yakutia Airlines and NordStar.\n🌎 Recall that in February 2025, air transportation on the Elga-Chita route was launched. Thanks to the new routes for delivering employees to the deposit, Elga Airport is now connected by air bridges with eight cities of Siberia and the Far East at once, including Neryungri, Yakutsk, Novosibirsk, Kemerovo, and Krasnoyarsk.\n🛬 In addition to expanding the route network, work is underway to improve the air harbor infrastructure. At the beginning of the year, a new aviation fueling complex was launched at the airport, and the terminal building underwent significant modernization. This will help improve passenger service quality and increase airport throughput.\n#Elga #Yakutia #ElgaAero"
    },
    24: {
        "zh": "「埃尔加为雅库特」：百万级故事\n🏆在雅库茨克的「穆斯塔尔」节上，「埃尔加为雅库特」竞赛的获奖者受到了表彰。这是雅库特历史上规模最大的一次面向创意团队、博主和媒体的竞赛。\n🌟记者和博主们在一年内讲述了「埃尔加煤炭」在共和国的社会项目。以这种形式发展共和国的创意潜力尚属首次：不仅评估创意想法的新颖性，还评估对议题的深入程度和参与度。\n「支持创意产业是对雅库特未来的投资。竞赛证明：关于善举的故事值得百万关注。我们相信，这样的倡议首先是对创意和想法活力的投资，是对我们地区可持续发展的投资，」——埃尔加公司新闻处负责人阿纳斯塔西娅·哈里托诺娃表示。\n\n祝贺获奖者！\n🎥 雅库特-萨哈通讯社——最佳多媒体专题项目。\n\n📰 Yakutia.Info——印刷/网络媒体类获奖者+观众选择奖！\n\n「这个竞赛不仅仅是关于采煤，而是关于真实的事迹：乐器、体育、IT教室。它还团结了我们的团队，」——雅库特-萨哈通讯社安德烈·尼基福罗夫\n「我们看到了商业、人民和媒体如何能够改变地区。这是其他公司的榜样，」——Yakutia.Info 丹尼斯·阿达莫夫",
        "en": "'Elga for Yakutia': Stories Worth Millions\n🏆 At the Muus Ustar festival in Yakutsk, the winners of the 'Elga for Yakutia' competition were awarded. This was the largest competition in the history of Yakutia for creative teams, bloggers, and media.\n🌟 Journalists and bloggers told about the social projects of Elga Coal in the republic throughout the year. The development of the republic's creative potential in this format was a first: not only the freshness of creative ideas was evaluated, but also the depth and involvement in the subject matter.\n'Supporting creative industries is an investment in the future of Yakutia. The competition proved that stories about good deeds deserve million-level attention. We are confident that such initiatives are, first and foremost, investments in the energy of ideas and creativity, in the sustainable development of our region,' noted Anastasia Kharitonova, head of the press service of Elga.\n\nCongratulations to the winners!\n🎥 Yakut-Sakha Information Agency — best multimedia special project.\n\n📰 Yakutia.Info — winner in the print/online media category + audience choice award!\n\n'This competition is not just about coal mining, but about real deeds: musical instruments, sports, IT classrooms. It also united our team,' — Andrey Nikiforov, YSIA\n'We saw how business, people, and media can change a region. This is an example for other companies,' — Denis Adamov, Yakutia.Info"
    },
    25: {
        "zh": "#本周视频：埃尔加矿床——雅库特真正的宝藏！\n⚡️ 位于萨哈共和国（雅库特）南部，距涅留恩格里市300公里；\n🌎 世界上最大的优质焦煤矿床之一；\n👨‍👩‍👧‍👦 按JORC标准储量为22亿吨；\n⛏️ 2024年开采量达到2800万吨；\n🏆 得益于该矿床的运营，雅库特进入俄罗斯煤炭开采量前二地区！\n🎥 视频：埃尔加公司\n⚡️ 订阅俄罗斯能源部",
        "en": "#VideoOfTheWeek: Elga Coal Deposit — a Real Treasure of Yakutia!\n⚡️ Located in the south of the Republic of Sakha (Yakutia), 300 km from the city of Neryungri;\n🌎 One of the world's largest deposits of premium coking coal;\n👨‍👩‍👧‍👦 Reserves amount to 2.2 billion tons according to JORC standards;\n⛏️ In 2024, production volume reached 28 million tons;\n🏆 Thanks to the operation of the deposit, Yakutia entered the TOP-2 regions of Russia in terms of coal production volume!\n🎥 Video: Elga\n⚡️ Subscribe to the Ministry of Energy of Russia"
    },
    26: {
        "zh": "「俄罗斯电网」为雅库特南部埃尔加煤炭集群的发展引入新的电网容量\n「俄罗斯电网」扩建了220千伏「埃尔加煤炭」变电站，并新建了一条长达268公里的输电线路，连接至220千伏「普里泽伊斯卡娅」供电中心。该项目提高了埃尔加集群的供电可靠性，该集群包括世界上最大的焦煤矿床之一，储量达22亿吨。未来向用户输送的电力将增加近2.5倍——从44兆瓦增至108兆瓦。\n埃尔加的开采始于2011年，但最初由柴油发电机组供电。2019年，企业接入俄罗斯统一能源系统。为此，「俄罗斯电网」建设了容量为125兆伏安的「埃尔加煤炭」变电站和220千伏「普里泽伊斯卡娅—埃尔加煤炭1号」线路。\n现在，变电站启用了第二台125兆伏安自耦变压器，与新线路220千伏「普里泽伊斯卡娅—埃尔加煤炭2号」协同工作。供电可靠性达到了第二类别，意味着拥有两个独立的电源。\n新建输电线路经过阿穆尔州泽伊区和萨哈共和国（雅库特）涅留恩格里区的领土。这是交通不便的地区，分布着永久冻土区、众多水域障碍（包括泽伊水库）、泥炭沼泽、山顶尖锐的山脉、陡峭的石质斜坡、深而狭窄的山谷。\n「俄罗斯电网」在国家项目——「主干基础设施现代化和扩建综合计划」框架内完成了必要工程。工程总造价达290亿卢布。电力供应覆盖了煤炭集群的所有主要设施：选煤厂、挖掘机、轮换营地、埃尔加机场和装载点。\n目前，公司正在进行用户接入容量增容工作，这将确保煤炭开采和加工量的增加……",
        "en": "Rosseti Introduced New Grid Capacities in Southern Yakutia for the Development of the Elga Coal Cluster\nRosseti expanded the 220 kV 'Elga Coal' substation and built a new 268 km power transmission line to the 220 kV 'Prizeyskaya' power center. The project improved the reliability of power supply to the Elga cluster, which includes one of the world's largest coking coal deposits with reserves of 2.2 billion tons. In the future, the power delivered to the consumer will increase almost 2.5 times — from 44 to 108 MW.\nMining at Elga began in 2011, but initially power supply was provided by diesel generator sets. In 2019, the enterprise was connected to the Unified Energy System of Russia. For this, Rosseti built the 'Elga Coal' substation with a capacity of 125 MVA and the 220 kV 'Prizeyskaya — Elga Coal No. 1' line.\nNow, a second 125 MVA autotransformer has been commissioned at the substation, which works in conjunction with the new 220 kV 'Prizeyskaya — Elga Coal No. 2' line. The second category of power supply reliability has been ensured, implying the presence of two independent power sources.\nThe route of the built transit passes through the territories of the Zeysky district of the Amur Oblast and the Neryungri district of the Republic of Sakha (Yakutia). This is a hard-to-reach area where permafrost zones are encountered, numerous water obstacles, including the Zeya reservoir, peat bogs, mountain ranges with sharp peaks, steep rocky slopes, deep and narrow valleys.\nRosseti completed the necessary work within the framework of the national project — the Comprehensive Plan for Modernization and Expansion of Backbone Infrastructure. The total cost of the work amounted to 29 billion rubles. Electricity is supplied to all main facilities of the coal cluster: processing plants, excavators, shift camps, Elga Airport, and loading points.\nCurrently, the company is working on increasing the consumer's connection capacity, which will ensure an increase in coal mining and processing volumes..."
    },
    27: {
        "zh": "埃尔加处于决策中心\n📊矿床启动了配备现代化监控、调度和自动化工具的「埃尔加」态势中心。\n中心的工作将确保选煤厂和采煤过程中技术流程的可靠高效控制。同时，它也是用于会议、演示和高质量视频会议的高级多媒体平台。\n态势中心的主要特点：\n➡️选煤厂全天候调度服务，控制技术流程的所有阶段；\n➡️由46块面板组成的视频墙，提供在任何时候观察整个选煤综合体运行的独特机会；\n➡️调度系统确保对采掘场车辆运输的控制、人员定位和综合视频监控，以提高安全性。\n🔗中心将公司的信息系统和工业设施整合到统一的网络基础设施中，用于实时数据交换和交互。",
        "en": "Elga at the Center of Decision-Making\n📊 A Situation Center 'Elga' has been launched at the deposit, equipped with modern monitoring, dispatching, and automation tools.\nThe center's work will ensure reliable and efficient control of technological processes at processing plants and during coal mining. It is also an advanced multimedia platform for conferences, presentations, and high-quality video conferencing.\nKey features of the situation center:\n➡️ Round-the-clock dispatching service for processing plants to control all stages of the technological process;\n➡️ A video wall of 46 panels provides a unique opportunity to observe the operation of the entire processing complex at any moment;\n➡️ Dispatching systems ensure control of vehicle transport at the open pit, personnel positioning, and comprehensive video surveillance to improve safety.\n🔗 The center unites the company's information systems and industrial facilities into a single network infrastructure for data exchange and interaction in real time."
    },
    28: {
        "zh": "✈️ 埃尔加航班秘籍\n2月，埃尔加-赤塔-埃尔加航线首航成功。\n波音737-800执飞。雅库特航空公司运送了214名乘客和近3000公斤行李及手提行李。\n该航线已纳入埃尔加矿床机场定期航班时刻表。\n航线网络扩展后，员工前往矿场的交通路线增至五条：赤塔、涅留恩格里、雅库茨克、新西伯利亚和克拉斯诺亚尔斯克。\n#埃尔加航空 #机场",
        "en": "✈️ Cheat Code for Elga\nIn February, the first flight on the Chita-Elga-Chita route took place.\nThe Boeing 737-800 performed the flight. Yakutia Airlines carried 214 passengers and almost 3,000 kg of baggage and hand luggage.\nThe route has been included in the regular flight schedule of Elga deposit airport.\nAfter expanding the route network, employee delivery to the deposit goes along five directions: Chita, Neryungri, Yakutsk, Novosibirsk, and Krasnoyarsk.\n#ElgaAero #Airport"
    },
    29: {
        "zh": "📈埃尔加矿床EKG-18R型挖掘机12号机组1月份装载了62.6万立方米土石方。这是该型号挖掘机在俄罗斯的纪录。\n装载量经测量工程师确认。据制造商——以P.G.科罗布科夫命名的「伊兹-卡尔泰克斯」公司数据，该型号挖掘机在全国任何露天矿场都未曾达到更高的生产率。\n🗓创纪录的成果得益于周密的作业计划、完善的物流、新设备和钻孔爆破技术的应用。\n「采场条件很好。物流也安排得很到位。结果白俄罗斯的贝拉兹自卸卡车没有停工。当然，团队合作、协调配合和精准执行也非常重要。我们之间心有灵犀，」——挖掘机12号司机米哈伊尔·谢苗诺夫讲述道。\n埃尔加EKG-18R挖掘机的平均采掘量为45-50万立方米。",
        "en": "📈 At the Elga coal deposit, the crew of excavator EKG-18R No. 12 shipped 626 thousand cubic meters of rock mass in January. This is a record for Russia for excavators of this model.\nThe shipment volume was confirmed by surveyor measurements. According to data from the manufacturer — IZ-KARTEX named after P.G. Korobkov, excavators of this brand have not achieved higher productivity at any open pit in the country.\n🗓 The record result was achieved thanks to clear work planning, well-thought-out logistics, application of new equipment and technology in drilling and blasting operations.\n'The face was good. Logistics were also well planned. As a result, BELAZs worked without downtime. And, of course, teamwork, coordination, and precision are of great importance. We understand each other from half a word,' tells excavator operator No. 12 Mikhail Semyonov.\nOn average, the excavation volume of EKG-18R excavators at Elga is 450–500 thousand cubic meters."
    },
    30: {
        "zh": "😀 埃尔加矿床「埃尔金」选煤厂的所有工厂已全面启动。11家工厂的年产能为3850万吨精矿。\n🚀煤炭精矿是高附加值产品。从采场出来的煤炭经过精心处理，改善了其特性并降低了灰分。\n🌐 高质量原材料对于满足公司产品消费者的要求非常重要，同时也有助于降低其在各行业使用时的环境负荷。\n#选煤厂",
        "en": "😀 All plants of the 'Elgin' processing plant complex at the Elga coal deposit have been launched. The annual capacity of eleven plants is 38.5 million tons of concentrate.\n🚀 Coal concentrate is a high value-added product. Coal from the face undergoes careful processing, which improves its characteristics and reduces ash content.\n🌐 High-quality raw materials are important for meeting the requirements of the company's product consumers, and also contribute to reducing the environmental load during its use in various industries.\n#ProcessingPlants"
    },
    31: {
        "zh": "😀 过去几个月，埃尔加发生了显著变化。发生了许多重要事件，实施了令人印象深刻的项目。其中之一就是太平洋铁路。\n在「俄罗斯」电视台的影片《通往海洋之路》中，我们讲述了这个雄心勃勃的基础设施项目的发展历程。埃尔加是强者的地方，这个故事展示了坚韧的劳动、创新的理念和团队精神如何将梦想变为现实。\n➡️了解更多关于太平洋铁路创建历程的信息，并从我们的成就中获得启发。",
        "en": "😀 Over the past months, Elga has noticeably transformed. Many significant events have taken place, impressive projects have been implemented. One of them is the Pacific Railway.\nIn the film 'Road to the Ocean' by the Russia TV channel, we tell about the development of our ambitious infrastructure project. Elga is a place for strong people, and this story demonstrates how persistent labor, innovative ideas, and team spirit turn dreams into reality.\n➡️ Learn more about the path of creating the Pacific Railway and be inspired by our achievements."
    },
    32: {
        "zh": "😀 2025年2月18日，「埃尔加」机场一天内接待了796名乘客\n🚀这是埃尔加矿床航空港运营以来单日乘客数量的最高纪录。\n同日还创下了单日加油量最高纪录——21.6吨。\n✈️此前2月，埃尔加机场启用了航空加油站，航站楼大楼进行了翻新，开通了埃尔加-赤塔航空运输新航线。\n这是运送员工前往矿场的第五条航线👷‍♀️👷‍♂️。\n此前已开通涅留恩格里、雅库茨克、新西伯利亚和克拉斯诺亚尔斯克航线🌐。",
        "en": "😀 On February 18, 2025, Elga Airport Served 796 Passengers\n🚀 This is the maximum number of people per day in the entire history of the air harbor of the Elga coal deposit.\nA maximum daily refueling volume was also recorded — 21.6 tons.\n✈️ Earlier in February, an aviation fueling complex was launched at Elga Airport, the terminal building was renovated, and a new air transportation route Elga — Chita was opened.\nThis is the fifth direction for delivering employees to the deposit 👷‍♀️👷‍♂️.\nPreviously, flights from Neryungri, Yakutsk, Novosibirsk, and Krasnoyarsk were launched 🌐."
    },
    33: {
        "zh": "埃尔加以全新的官方频道重返Telegram：独家新闻、公司前景项目的发展动态📈以及一键获取的实用材料。\n这不仅仅是回归——这是一个新的篇章，传统与创新相遇，我们的创意能量直接传递到您的智能手机屏幕上。加入我们，与同事、专家和朋友分享频道链接，成为首批了解我们如何开辟未来道路的人！🚀\n让我们一起点燃这个数字之火，证明煤炭的力量不仅在于其威力，还在于创新的沟通方式。点击「订阅」，与我们一起站在积极变革的浪潮上！📲",
        "en": "Elga Returns to Telegram with an Updated Official Channel: exclusive news, development status of the company's promising projects 📈 and useful materials at the touch of a button.\nThis is not just a return — it is a new chapter where tradition meets innovation, and the energy of our ideas is transmitted directly to your smartphone screen. Join us, share the channel link with colleagues, experts, and friends, and be the first to know how we are paving the way to the future! 🚀\nLet's light this digital fire together and prove that the power of coal is not only in its might, but also in an innovative approach to communication. Click 'Subscribe' and ride the wave of positive change with us! 📲"
    },
}


def main():
    with open('src/data/telegramNews.json', 'r', encoding='utf-8') as f:
        data = json.load(f)

    for i, msg in enumerate(data['messages']):
        ru_text = msg['text']
        t = translations.get(i, {})
        msg['text'] = {
            'ru': ru_text,
            'zh': t.get('zh', ru_text),
            'en': t.get('en', ru_text),
        }

    with open('src/data/telegramNews.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Updated {len(data['messages'])} messages with trilingual support.")


if __name__ == '__main__':
    main()
